include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    comment_references: true
    flutter_style_todos: true
    omit_local_variable_types: true
    prefer_relative_imports: true
    prefer_double_quotes: true
    prefer_final_in_for_each: true
    parameter_assignments: true
    prefer_foreach: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_const_constructors: true
    unnecessary_lambdas: true
    unnecessary_raw_strings: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_parenthesis: true
    use_colored_box: true
    use_decorated_box: true
    use_named_constants: true
    use_raw_strings: true
    use_string_buffers: true
